### ISSUE TITLE
Install fails on Windows 8

### ISSUE THREAD

**Issue by rbaprado** [selectize/selectize.js#846]
```
D:\buzz\Projetos\mobtag_lab>npm install selectize --save
|


> microtime@1.2.0 install D:\buzz\Projetos\mobtag_lab\node_modules\selectize\node_modules\sifter\node_modules\microtime
> node-gyp rebuild


D:\buzz\Projetos\mobtag_lab\node_modules\selectize\node_modules\sifter\node_modules\microtime>if not defined npm_config_
node_gyp (node "C:\Program Files\iojs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" re
build )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  microtime.cc
d:\buzz\projetos\mobtag_lab\node_modules\selectize\node_modules\sifter\node_modules\microtime\node_modules\nan\nan_impl
ementation_12_inl.h(172): error C2660: 'v8::Signature::New' : function does not take 4 arguments [D:\buzz\Projetos\mobt
ag_lab\node_modules\selectize\node_modules\sifter\node_modules\microtime\build\microtime.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\iojs\node_modules\npm\node_modules\node-gyp\lib\build.js:269
:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:199:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\node_modules\\node-gyp
\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\buzz\Projetos\mobtag_lab\node_modules\selectize\node_modules\sifter\node_modules\microtime
gyp ERR! node -v v2.2.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install
" "selectize" "--save"
npm ERR! node v2.2.1
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! microtime@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the microtime@1.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\buzz\Projetos\mobtag_lab\npm-debug.log
```

**Comment by gionkunz** [comment]
This PR will solve it making microtime an optional dependency in sifter https://github.com/brianreavis/sifter.js/pull/28

**Comment by joallard** [comment]
Closing this as this seems to be Sifter territory
